namespace tableMenu{
    public enum GuideWindownBtn{
        main_shoufeizhan = 1,//主界面的第一个航道的收费站
        facility_jiushengting = 2,//设施界面解锁救生艇
        facility_jiushengquan = 3,//设施界面解锁救生圈
        facility_diaotai = 4,//设施界面解锁吊台
        main_task = 5,//主界面任务标识
        ship_first_unlock = 6,//船舶图鉴第一个解锁
        ship_unlock_sure = 7,//船舶解锁确认
        main_task_get = 8,//主界面任务奖励领取
        main_ship = 9,//主界面船舶图鉴
        ship_first_uplevel = 10,//船舶图鉴第一个强化按钮
        ship_close = 11,//船舶图鉴关闭按钮
        main_staff = 12,//主界面职员
        staff_first_unlock = 13,//职员界面第一个解锁按钮
        main_nurture = 14,//主界面养护
        nurture_first_unlock = 15,//养护界面第一个解锁按钮
        nurture_close = 16,//养护界面关闭按钮
        main_call_business = 17,//主界面招商
        zhaoshang_first_unlock = 18,//招商第一个解锁按钮
        zhaoshang_info = 19,//招商查看签约按钮
        zhaoshang_info_sign = 20,//招商查看签约的签约按钮
        zhaoshang_close = 21,//招商关闭按钮
        main_fuli = 22,//福利界面
        fuli_upspeed = 23,//福利过闸加速
        main_clean = 24,//主界面清洗航道
        main_jiaotong = 25,//主界面指挥交通
        jiaotong_first_challenge = 26,//交通指挥挑战
        jiaotong_info = 27,//港口拥堵某一个船
        main_pintu = 28,//装卸货物
        pintu_challenge = 29,//装卸货物挑战
        main_fix = 30,//主界面船舶检修
        fix_challenge = 31,//检修挑战
        main_navigate = 32,//主界面航运
        navigate_first_unlock = 33,//航运第一个船舶解锁
        navigate_order = 34,//航运订单按钮
        navigate_order_send = 35,//航运订单发货
        main_navigate_animation = 36,//主界面航运标识
        main_staff_lv_up = 37,//主界面培训按钮
        staff_lv_up_first_train = 38,//培训界面第一个培训
        staff_lv_up_one_max = 39,//培训员工详情看广告拉满
        main_dam = 40,//主界面大坝
        dam_unlock = 41,//大坝解锁
        main_collect = 42,//藏品
        main_ach = 43,//成就
        main_longzhou = 44,//赛龙舟
        main_adday = 45,//领奖
        main_facility = 46,//主界面设施
    //=======代码自动生成请勿修改=======
    }
}